accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .views import SignUpView, CustomLoginView

app_name = 'accounts'

urlpatterns = [
	path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

cart/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('cart/', include('shopping_cart.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from products import views
from .views import product_list
from .views import index

from django.contrib import admin
from django.urls import path,include
from products import views


app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_list', views.product_list, name='product_list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    
]

accounts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save

from products.models import Product

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ebooks = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

accounts/views.py
from django.shortcuts import render, get_object_or_404

from shopping_cart.models import Order
from .models import Profile

from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView

def my_profile(request):
	my_user_profile = Profile.objects.filter(user=request.user).first()
	my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
	context = {
		'my_orders': my_orders
	}

	return render(request, "profile.html", context)



class SignUpView(CreateView):

    template_name = 'accounts/signup.html'

    form_class = UserCreationForm

    success_url = reverse_lazy('products:product_list')

    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        login(self.request, user)

        return to_return

class CustomLoginView(LoginView):

    template_name = 'accounts/login.html'

accounts/templates/accounts/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    
</head>
<body>
    <aside>
        <header>
          <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'products:index' %}">Project App</a>
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div
                class="collapse navbar-collapse flex-row-reverse"
                id="navbarTogglerDemo02"
              >
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'products:product_list' %}">Заявки</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="#">Hi {{user.username}}</a>
                  </li>
                  <li class="nav-item">
                    <div class="nav-link active">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-sm btn-danger" 
                      >Выход</a>
                    </div>
                  </li>
                  
                  {% else %}
          
                  <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="btn btn-sm btn-danger"
                      >Войти</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </header>
    </aside>


    <main>
    {% block content %}
    {% endblock %}
    </main>
   


   <aside>
     <div>
    <footer class="bg-dark text-center text-white" id="footer">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-square"></i></a>
      
            <!-- VK -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-vk"></i></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Steam -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-steam"></i></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
       
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: #212529;">
          © 18.07.2021 Токмок:
          <a class="text-white" href="https://namaz.today/city/sadovoe-chujskij-rajon">3:50</a>
        </div>
      </footer>
    </div>
   </aside>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %} 

{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Вход в систему</h1>
</div>
<div class="container">
<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post" >
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Войти</button>
    </form>
  </div>
  {% comment %}  Уже зарегистрирован {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Нету аккаунта?
      <a href="{% url 'accounts:signup' %}" class="text-primary ml-2">Создать аккаунт</a>
    </p>
  </div>
</div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %} 
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Регистрация</h1>
</div>
<div class="container">
<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Создать аккаунт</button>
    </form>
  </div>
  {% comment %}  Уже зарегистрирован {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Уже зарегистрирован?
      <a href="{% url 'accounts:login' %}" class="text-primary ml-2"> Вход в систему </a>
    </p>
  </div>
</div>
</div>
{% endblock content %}