cart/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('cart/', include('shopping_cart.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path
from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
    path('order-summary/$', views.order_details, name="order_summary"),
    path('success/$', views.success, name='purchase_success'),
    path('item/delete/(?P<item_id>[-\w]+)/$', views.delete_from_cart, name='delete_item'),
    path('checkout/$', views.checkout, name='checkout'),
    path('payment/(?P<order_id>[-\w]+)/$', views.process_payment, name='process_payment'),
    path('update-transaction/(?P<order_id>[-\w]+)/$', views.update_transaction_records, name='update_records'),

]

shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    # payment_details = models.ForeignKey(Payment, null=True)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.data for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

shopping_cart/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Profile
from products.models import Product

from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order


def get_user_pending_order(request):
    # получить заказ для нужного пользователя
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # получить единственный заказ в списке отфильтрованных заказов
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # получить профиль пользователя
    user_profile = get_object_or_404(Profile, user=request.user)
    # фильтровать продукты по идентификатору
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    # проверить, владеет ли пользователь уже этим продуктом
    if Order.objects.filter(owner=user_profile).exists():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('products:product_list')) 
    if product in request.user.profile.ebooks.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('products:product_list')) 
    # создать OrderItem выбранного продукта
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # создать заказ, связанный с пользователем
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # генерировать справочный код
        user_order.ref_code = generate_order_id()
        user_order.save()

    # показать подтверждающее сообщение и перенаправить обратно на ту же страницу
    messages.info(request, "item added to cart")
    return redirect(reverse('shopping_cart:order_summary'))

@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
    }
    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def process_payment(request, order_id):
    # обработать платеж
    return redirect(reverse('shopping_cart:update_records',
                    kwargs={
                        'order_id': order_id,
                    })
                )


@login_required()
def update_transaction_records(request, order_id):
    # получить обрабатываемый заказ
    order_to_purchase = Order.objects.filter(pk=order_id).first()

    # обновить размещенный заказ
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()
    
    # получить все элементы в порядке - формирует набор запросов
    order_items = order_to_purchase.items.all()

    # обновление элементов заказа
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Добавление продуктов в профиль пользователя
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()

    #====== TODO: Update Payment records ========

    # отправить электронное письмо клиенту
    messages.info(request, "Thank you! Your items have been added to your profile")
    return redirect(reverse('products:product_list'))


def success(request, **kwargs):
    # представление, означающее, что транскрипция прошла успешно
    return render(request, 'shopping_cart/purchase_success.html', {})

shopping_cart/templates/shopping_cart/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
    table.borderless td,table.borderless th{
       border: none !important;
    }
</style>

 <section>
    <div class="row" id="tablerow">
    <div class="col-md-8 col-xs-12">
      <table class="table">
        <tr>
          <td><h4>Order Summary</h4></td>
        </tr>
        <tr>
          <td>
            {% for item in order.get_cart_items %}
              <tr>
                <td>{{ item }}</td>
                
              </tr>
            {% endfor %}
          </td>
        </tr>

      </table>
        <form method="POST" action="{% url 'shopping_cart:process_payment' order.id %}">
          {% csrf_token %}
          <button style="width: 100%; float: left;" class="btn btn-warning">Забронировать11</button>
          
        </form>
        <!-- for another day -->
        
    </div>
   </div>
  <!-- </form> -->
 </section>
{% endblock content %}

{% block scripts %}
  {{ block.super }}

  <!-- initialize jQuery Library -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap jQuery -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      
{% endblock scripts %}

shopping_cart/templates/shopping_cart/order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        <td colspan=3>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:process_payment' order.id %}" class="pull-right btn btn-primary">Отправить заявку</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}