cart/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('cart/', include('shopping_cart.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from products import views
from .views import product_list
from .views import index

from django.contrib import admin
from django.urls import path,include
from products import views


app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_list', views.product_list, name='product_list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Product(models.Model):
    GENDER_CATEGORIES= [
        ('Male', 'Мужчина'),
        ('Female', 'Женщина'),     
    ]
    name = models.CharField('имя',max_length=20)
    secondname = models.CharField('фамилия',max_length=120)
    manid = models.IntegerField('ID')
    gender = models.CharField(max_length=50, choices= GENDER_CATEGORIES)

    data = models.CharField(max_length=10)

    def __str__(self):
        return self.name

products/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Product
from shopping_cart.models import Order
from django.urls import reverse_lazy


from django.views.generic import CreateView 
from django.shortcuts import get_object_or_404


class ProductCreateView(CreateView):
    model = Product
    fields= '__all__'
    success_url = reverse_lazy("products:product_list")


def index(request):
    return render(request, "products/index.html")

def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "products/product_list.html", context)

products/templates/products/index.html
{% extends 'accounts/base.html' %} 


{% block content %}
<div class="mx-auto">
    <h1 class="mt-3 text-center">Главная страница</h1>
  </div>
  <br>
  <br>
    {{ message }}
    {% if user.is_authenticated %}
    <div class="deff-button">
        <a href="{% url 'products:create'%}" class="button"><li><button class="btn btn-info"> <i class="fas fa-plus-circle"></i>Добавить заявку</button></li></a>
        </div>
    {% else %}
    <h2>Вы не авторизованы!</h2>
    {% endif %}
           
{% endblock content %}

products/templates/products/product_form.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="mx-auto">
    <h1 class="mt-3 text-center">Подать заявку</h1>
  </div>
  <br>
  <br>
  <div class="form-group">
    <div class="container">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <div class="deff-button">
    <button type="submit" class="btn btn-success mb-3">Добавить</button>
    </div>
  </form>
</div>  
{% endblock content %}

products/templates/products/product_list.html
{% extends 'accounts/base.html' %} 


{% block content %}
<div class="mx-auto">
    <h1 class="mt-3 text-center">Главная страница</h1>
  </div>
  <br>
  <br>
    <div>
    <div class="">
    {% for object in object_list %}
        <div class="" id="block">
            <p>Заявка на общежитие</p>
            <p>{{ object.name }}</p>
        </div>
    {% endfor %}
           
{% endblock content %}